title: Nicolas Pascual
description: Personal web page and blog of Nicolás Pascual, junior developer interested in everything related to programming.

url: http://nicolas-pascual.com
baseurl: ""
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: []

navigation:
 - title: Home
   url: /index.html
 - title: Blog
   url: /bindex
 - title: About
   url: /about

social:
   github: nicolaspascual
   twitter: nicolaspascualg
   email: nicolaspascualgonzalez@gmail.com

google_analytics: "UA-105238956-1"
